### ISSUE TITLE
Forward Link component's ref.

### ISSUE THREAD

**Issue by abdullaev388** [atomic-router/react#12]
https://github.com/atomic-router/react/blob/d2c936dea41b50ad933afb7eeab2f2aba0e42bf9/src/link.tsx?rgh-link-date=2022-09-08T13%3A55%3A34Z#L17

Some ui frameworks require components to forward ref, otherwise react will throw an error:
```Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?```

**Comment by sergeysova** [comment]
@abdullaev388 What the case you need ref for the link?

**Comment by abdullaev388** [comment]
[Added](https://github.com/atomic-router/react/pull/16)
