### ISSUE TITLE
Could not find a types declaration

### ISSUE THREAD

**Issue by raidenmiro** [atomic-router/react#18]
In this code example I get an error related to types

![image](https://github.com/atomic-router/react/assets/82271383/a072fda3-26f4-403f-bbd6-e0e206a3344b)

Error message

![image](https://github.com/atomic-router/react/assets/82271383/04312a5a-5e5a-40d3-bb6d-c703dbe22c92)

Installed versions

- `atomic-router` - 0.8.0
- `atomic-router-react` - 0.8.1

Suggestion on how to fix this

- Add type declaration to exports 

![image](https://github.com/atomic-router/react/assets/82271383/6e1af36e-1b17-4d62-81cf-5d6067956ed7)

**Comment by sergeysova** [comment]
@raidenmiro Thank you for the report.
I am released https://github.com/atomic-router/react/releases/tag/v0.8.2
Would you like to try it?

**Comment by raidenmiro** [comment]
Thanks a lot for the fix. But it doesn't work :smile:, because missed `./` in this line
https://github.com/atomic-router/react/blob/809d67394c4ac2e4af641806d3e9d621225fa81a/package.json#L19

**Comment by sergeysova** [comment]
Oh, my bad.
Let's try again with https://github.com/atomic-router/react/releases/tag/v0.8.3

**Comment by raidenmiro** [comment]
@sergeysova It works! Thanks
